apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-tls-api
spec:
  entryPoints:
    - websecure
  tls:
    secretName: {{ .Values.deploymentDomain }}-tls
  routes:
    - match: "Host(`{{ .Values.deploymentDomain }}`) && PathPrefix(`/api`)"
      kind: Rule
      middlewares:
        - name: {{ .Chart.Name }}-strip-api-prefix
      services:
        - name: {{ .Chart.Name }}-api
          port: 80

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-api
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`{{ .Values.deploymentDomain }}`) && PathPrefix(`/api`)"
      kind: Rule
      middlewares:
        - name: {{ .Chart.Name }}-redirect
      services:
        - name: {{ .Chart.Name }}-api
          port: 80