apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-api
  labels:
    app: {{ .Chart.Name }}-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-api
    spec:
      serviceAccountName: rope
      containers:
        - name: {{ .Chart.Name }}-api
          image: {{ .Values.apiImage.name }}:{{ .Values.apiImage.tag }}
          command: ["uvicorn", "rope.api.main:app", "--host", "0.0.0.0", "--port", "80", "--timeout-keep-alive", "120"]
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: pgUsername
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: pgPassword
            - name: SESSION_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: sessionSecretKey
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: googleClientId
            - name: MOODLE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: moodleToken
            - name: POSTGRES_SERVER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: pgServer
            - name: MOODLE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: moodleUrl
            - name: POSTGRES_DB
              value: {{ .Values.pgDatabase }}
            - name: SQS_QUEUE
              value: {{ .Values.sqsQueue }}
            - name: COURSES_CSV_S3_BUCKET
              value: {{ .Values.coursesCsvS3Bucket }}
            - name: COURSES_CSV_S3_KEY
              value: {{ .Values.coursesCsvS3Key }}
          ports:
            - containerPort: 80