apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-processor
  labels:
    app: {{ .Chart.Name }}-processor
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-processor
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-processor
    spec:
      serviceAccountName: rope
      containers:
        - name: {{ .Chart.Name }}-processor
          image: {{ .Values.apiImage.name }}:{{ .Values.apiImage.tag }}
          imagePullPolicy: Always
          command: ["rope-course-processor"]
          args: ["--daemonize"]
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: pgUsername
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: pgPassword
            - name: MOODLE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: moodleToken
            - name: POSTGRES_SERVER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: pgServer
            - name: MOODLE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: moodleUrl
            - name: POSTGRES_DB
              value: {{ .Values.pgDatabase }}
            - name: SQS_QUEUE
              value: {{ .Values.sqsQueue }}
            - name: SQS_POLL_INTERVAL_MINS
              value: "{{ .Values.processorPollIntervalMins }}"
