apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
stringData:
  pgUsername: {{ .Values.pgUsername }}
  pgPassword: {{ .Values.pgPassword }}
  googleClientId: {{ .Values.googleClientId }}
  sessionSecretKey: {{ .Values.sessionSecretKey }}
  moodleToken: {{ .Values.moodleToken }}
