"""Update CourseBuildStatus enum subclass

Revision ID: 088ef8066747
Revises: 53c35d1a2408
Create Date: 2024-02-26 12:29:29.940340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088ef8066747'
down_revision = '53c35d1a2408'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
