"""Update column names

Revision ID: ece1292c9bdc
Revises: 53c35d1a2408
Create Date: 2024-02-28 16:40:18.214086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece1292c9bdc'
down_revision = '53c35d1a2408'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_build', sa.Column('school_district_id', sa.Integer(), nullable=False))
    op.add_column('course_build', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.drop_constraint('course_build_creator_fkey', 'course_build', type_='foreignkey')
    op.drop_constraint('course_build_school_district_fkey', 'course_build', type_='foreignkey')
    op.create_foreign_key(None, 'course_build', 'school_district', ['school_district_id'], ['id'])
    op.create_foreign_key(None, 'course_build', 'user_account', ['creator_id'], ['id'])
    op.drop_column('course_build', 'school_district')
    op.drop_column('course_build', 'creator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_build', sa.Column('creator', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('course_build', sa.Column('school_district', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'course_build', type_='foreignkey')
    op.drop_constraint(None, 'course_build', type_='foreignkey')
    op.create_foreign_key('course_build_school_district_fkey', 'course_build', 'school_district', ['school_district'], ['id'])
    op.create_foreign_key('course_build_creator_fkey', 'course_build', 'user_account', ['creator'], ['id'])
    op.drop_column('course_build', 'creator_id')
    op.drop_column('course_build', 'school_district_id')
    # ### end Alembic commands ###
