"""Update column names

Revision ID: ece1292c9bdc
Revises: 53c35d1a2408
Create Date: 2024-02-28 16:40:18.214086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece1292c9bdc'
down_revision = '53c35d1a2408'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_build', column_name='creator', new_column_name='creator_id')
    op.alter_column('course_build', column_name='school_district', new_column_name='school_district_id')
    op.drop_constraint('course_build_creator_fkey', 'course_build', type_='foreignkey')
    op.drop_constraint('course_build_school_district_fkey', 'course_build', type_='foreignkey')
    op.create_foreign_key(None, 'course_build', 'school_district', ['school_district_id'], ['id'])
    op.create_foreign_key(None, 'course_build', 'user_account', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_build', column_name='creator_id', new_column_name='creator')
    op.alter_column('course_build', column_name='school_district_id', new_column_name='school_district')
    op.drop_constraint('course_build_creator_id_fkey', 'course_build', type_='foreignkey')
    op.drop_constraint('course_build_school_district_id_fkey', 'course_build', type_='foreignkey')
    op.create_foreign_key(None, 'course_build', 'school_district', ['school_district'], ['id'])
    op.create_foreign_key(None, 'course_build', 'user_account', ['creator'], ['id'])
    # ### end Alembic commands ###
