---
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  backend:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: pip install .[test]
      - name: Lint
        run: flake8
      - name: Test
        run: pytest --cov-report=term --cov-report=xml --cov=rope
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3

  frontend:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
      - name: Setup
        run: npm install
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
